pipeline {
    agent none
    stages {
        stage('EC2 Instances') {
            agent {
                label 'Aws-ec2-instances'
            }
            steps {
                sh 'terraform init'
                sh 'terraform apply -target=module.ec2 --auto-approve'
            }
        }
        stage('S3 Bucket') {
            agent {
                label 'Aws-s3-Bucket'
            }
            steps {
                sh 'terraform init'
                sh 'terraform apply -target=module.s3 --auto-approve'
            }
        }
        stage('IAM User') {
            agent {
                label 'Aws-iam'
            }
            steps {
                sh 'terraform init'
                sh 'terraform apply -target=module.iam --auto-approve'
            }
        }
        stage('DynamoDB Table') {
            agent {
                label 'Aws-dynamodb'
            }
            steps {
                sh 'terraform init'
                sh 'terraform apply -target=module.dynamodb --auto-approve'
            }
        }
        stage('Github') {
            agent {
                label 'Aws-github'
            }
            steps {
                sh 'terraform init'
                sh 'terraform apply -target=module.github --auto-approve'
            }
        }
    }
}